### ISSUE TITLE
As a reviewer of JOSS, I want more permissive commits to be allowed by the NASA PDS Engineering Node

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/.github#14]
## 💪 Motivation

See [this issue](https://github.com/openjournals/joss-reviews/issues/4327) for context; apparently some reviewer of JOSS thinks our contributor guidelines are too strict when it comes to pull-requests that contain cosmetic changes only. This person believes that [PEP8](https://peps.python.org/pep-0008/) changes should be allowed even though they are cosmetic.

## ⚖️ Acceptance Criteria

**Given** a pull-request that has cosmetic-only changes but are actually PEP8 changes
**When I perform** a merge
**Then I expect** the merge to be allowed and not rejected based on new contributor guidelines that contains such verbiage.

## ⚙️ Engineering Details

I personally think a reviewer at a journal doesn't have the authority to dictate what our contributor guidelines are, but Marc seemed pretty invested in the reviewer's comments, and so we can track, discuss, and ultimately decide what to do with this punctilious pronouncement and any changes to our guidelines here.

**Comment by SimonMolinsky** [comment]
Hi @nutjob4life ,

I think we've stepped too far from the initial context of the issue, so maybe we should take a step back and look into it? 

1) I was reviewing the Python package submitted to the journal, not the whole ecosystem, where the package is only a small part.
2) But package refers to the Contributing Guidelines from the ecosystem.
3) The code in the package is slightly incosistent with PEP8, which could lead to future bugs, but the package works fine.
4) I don't know where we should draw a line between cosmetic changes and code usability - from my perspective, it is PEP8 that defines styling too. Suppose a package is published as an Open Source, but its code is hard to read, especially in a scripting language like Python. In that case, we may stop devs outside the organization from joining in development. Python is - if we like it or not - a language where syntax is essential.

But I understand your opinion. Anyway, I have politely asked/suggested to include info about PEP8, and it wasn't any condition to end the review. Your final decision won't affect the review in any way - it's up to you and you only, as you have written `I personally think a reviewer at a journal doesn't have the authority to dictate what our contributor guidelines`, and I agree with that. The last thing that I want to do is to force someone to do meaningless work. If you feel it's not ok, close the issue and forget about it.

Thanks!

**Comment by jordanpadams** [comment]
thanks for the input and discussion @SimonMolinsky and @nutjob4life . I think we are going to close this as wontfix for now, and if we get another user that finds our guidelins to be too strict, we can revisit.

thanks again!
