### ISSUE TITLE
Visibility of the default community health files

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/.github#7]
After reviewing the visibility of the default community health files I'm not convinced that they're prominent enough without additional linking on our part. I reread the GitHub documentation and I can both see where they accurately described the functionality and why I expected something different. I'd have liked to see references to the files off the main landing page for a repository but I can't find that anywhere.

I'd suggest that we update our template repos to link to these defaults in appropriately named README sections or something similar. Thoughts?

--

These are the only places where I can find references to our default files:
![Screen Shot 2021-08-26 at 09 16 55](https://user-images.githubusercontent.com/860902/131000598-5c0de78b-21f9-4cc9-aaf7-5956d2b35160.png)

References are also available to the files on the Community Insights page but that seems way too nested for anyone to care.
![Screen Shot 2021-08-26 at 09 17 58](https://user-images.githubusercontent.com/860902/131000681-e3edea6b-55a9-4f35-a7d3-6d81b892ab72.png)

**Comment by nutjob4life** [comment]
I think we can mark this as done? 🤷‍♀️

When I visit a pds-repository that I've *been to before* and try to submit a new issue or pull request, I get this helpful box:

![Screen Shot 2021-09-09 at 10.58.33 AM.png](https://images.zenhubusercontent.com/5d52e426b9ebc816204aa77d/365e9c41-2ba6-45af-b250-2a886a526750)

Similarly, for pds-repositories I've *never* used, I get this box:

![Screen Shot 2021-09-09 at 10.59.11 AM.png](https://images.zenhubusercontent.com/5d52e426b9ebc816204aa77d/18cf3861-ef8b-41bf-9fa0-2ea33a9c9aac)

And the pds-template repository for Python has:

 ![Screen Shot 2021-09-09 at 11.00.35 AM.png](https://images.zenhubusercontent.com/5d52e426b9ebc816204aa77d/603c4a63-e7dc-4b5e-880b-94794b4e07bb)

While the pds-template repository for Java has:

![Screen Shot 2021-09-09 at 11.00.48 AM.png](https://images.zenhubusercontent.com/5d52e426b9ebc816204aa77d/907dd257-2bcd-4049-99fa-fbb4228e894b)

Any other ideas towards community health visibility? 💡❔

**Comment by jordanpadams** [comment]
👍

**Comment by MJJoyce** [comment]
:+1:, didn't get closed out after some of the related tickets got resolved. Thanks for catching it!
